# Site-wide settings
# ------------------

title: MORESCODE ANALYTICS LLC
author:
  name: Paul Moresco
  email: hello@morescode-analytics.com
description: |
  Full-service data science, analytics, and statistical consulting.

url: "https://www.morescode-analytics.com"
baseurl: ""  # Leave empty if deploying at the root domain
destination: docs

remote_theme: jekyll/minima@8106bd4
minima:
  skin: auto
  nav_pages:
    - about.md
    - portfolio.md

  show_excerpts: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/morescode-pm"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/paul-moresco"
    - title: Kaggle
      icon: kaggle
      url: "https://www.kaggle.com/morescope/"
    - title: Tableau Public
      icon: salesforce
      url: "https://public.tableau.com/app/profile/paul.moresco/vizzes"
  hide_site_feed_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote_theme

include:
  - CNAME

paginate: 3
paginate_path: "/page/:num"
future: true