# Site-wide settings
# ------------------

title: MORESCODE ANALYTICS LLC
author:
  name: Paul Moresco
  email: hello@morescode-analytics.com
description: |
  Full service data science, analytics, and statistical consulting.  
  FREE 5 minute answers!
destination: docs

remote_theme: jekyll/minima@8106bd4

minima:
  skin: solarized
  nav_pages:
    - about.md
    - projects.md
  show_excertps: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/morescode-pm"
    - title: Linkedin
      icon: linkedin
      url: "www.linkedin.com/in/paul-moresco"
  hide_site_feed_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote_theme


exclude:
  - docs_backup/*